---
--- Generated by Luanalysis
--- Created by a.
--- DateTime: 2026/3/19 20:36
---

-- 比较线程标识与锁中标识是否一致
if (redis.call('get', KEYS[1]) == ARGV[1]) then
    -- 释放锁 del key
    return redis.call('del', KEYS[1])
else
    return 0
end